services:
  postgres_db:
    container_name: "postgres_db"
    image: postgres:latest
    environment:
      - POSTGRES_DB=pickwisely_dev
      # TODO: Use env variable for this
      - POSTGRES_PASSWORD=123
    volumes:
      - ./database/01_table_schemas.sql:/docker-entrypoint-initdb.d/01_table_schemas.sql
      - ./database/02_seed_data.sql:/docker-entrypoint-initdb.d/02_seed_data.sql
    ports:
      - "5432:5432"
  fastapi_backend:
    container_name: "fast_api" 
    build: ./backend
    depends_on:
    - postgres_db
    volumes:
    - ./backend:/app
    ports:
    - "8000:8000"